# Generated by Django 5.0.3 on 2024-05-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
