# Generated by Django 5.0.3 on 2024-04-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('P', 'P'), ('B', 'B')], default='P', max_length=1),
        ),
    ]
