# Generated by Django 5.0.3 on 2024-05-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyprofile_bio_personalprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
