# Generated by Django 5.0.3 on 2024-04-15 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_profile_bi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bi',
            new_name='identification_number',
        ),
    ]
