# Generated by Django 5.0.3 on 2024-04-27 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
