# Generated by Django 5.0.3 on 2024-05-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_companyprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
