# Generated by Django 5.0.3 on 2024-04-15 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sector_personalprofile_companyprofile_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['name', 'created_at'], 'verbose_name_plural': 'Sectores Empresarial'},
        ),
        migrations.RenameField(
            model_name='personalprofile',
            old_name='identification_number',
            new_name='bi',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='phone',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
