from .personal_information_form import PersonalInformationForm, PersonalProfileInformationForm
from .personal_formation_form import AcademicFormationForm, ProfissionalFormationForm
from .personal_experience_form import ProfissionalExperienceForm