# Generated by Django 5.0.3 on 2024-05-12 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='benefits',
        ),
    ]
