# Generated by Django 5.0.3 on 2024-05-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_vacancy_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(blank=True, upload_to='perfil'),
        ),
    ]
