# Generated by Django 5.0.3 on 2024-05-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_vacancy_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='job_position',
            new_name='job_type',
        ),
    ]
