# Generated by Django 5.0.3 on 2024-05-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_rename_job_position_vacancy_job_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Responsability',
            new_name='Responsibility',
        ),
    ]
