# Generated by Django 5.0.3 on 2024-05-18 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_skill_options_benefit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='candidates', to=settings.AUTH_USER_MODEL),
        ),
    ]
