# Generated by Django 5.0.3 on 2024-05-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_profissionalexperienceitem_profissionalexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalexperienceitem',
            name='profissional_experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profissional_experience_item', to='personal.profissionalexperience'),
            preserve_default=False,
        ),
    ]
