# Generated by Django 5.0.3 on 2024-05-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_profissionalexperienceitem_profissional_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalexperienceitem',
            name='years',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
