# Generated by Django 5.0.3 on 2024-05-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_alter_documentation_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademicInstituition',
            new_name='AcademicInstitution',
        ),
        migrations.RenameModel(
            old_name='ProfissionalInstituition',
            new_name='ProfissionalInstitution',
        ),
        migrations.AlterModelOptions(
            name='academicformationitem',
            options={'ordering': ['course'], 'verbose_name_plural': 'Formação Academica'},
        ),
        migrations.AlterModelOptions(
            name='academicinstitution',
            options={'ordering': ['name'], 'verbose_name_plural': 'Instituições Academicas'},
        ),
    ]
